### Transfer Entropy analysis code

In the first part I upgrade dit package for Python. This package has defined the functions to compute time-delayed mutual information and transfer entropy using time series as inputs.

In [75]:
# Install the upgrade from git
#!pip install --user --upgrade git+git://github.com/dit/dit.git#egg=dit

**Step 1**

To work with this code correctly we need to import all the packages needed in Python. It is important to notice that this package is designed for the use of discrete variables. dit stands for discrete information theory.

In [76]:
# Import the packages numpy, dit, and collections to run the code
import numpy as np

from collections import namedtuple

import dit
from dit.inference import binned, dist_from_timeseries
from dit.multivariate import total_correlation as I, intrinsic_total_correlation as IMI

dit.ditParams['repr.print'] = True

**Step 2**

Here we create a function to obtain the time-delayed mutual information and transfer entropy at the same time

In [77]:
#Definition of the tuple to save the time-delayed mutual information and transfer entropy
TimeDelayed = namedtuple('TimeDelayed', ['timedelayedMU', 'transferE'])

#Function to compute the time-delayed mutual information and transfer entropy
def get_timedelayed(ts, length):

    d = dist_from_timeseries(ts, history_length=length)

    i_past, j_past, i_pres, j_pres = [0], [1], [2], [3]

    timedelayedMU = I(d, [i_past, j_pres])
    transferE = I(d, [i_past, j_pres], j_past)

    return TimeDelayed(timedelayedMU, transferE)

**Step 3**

We create three different simulations to calculate the time-delayed mutual information and the transfer entropy showing that is possible to make these measures similar or different between them

In [78]:
#Function for the first simulation. If we think about time series X and Y in this case the present of Y is always equal to the past of X
def get_exemplar_1(length):

    xs = np.random.randint(2, size=length)
    ys = np.roll(xs, 1)
    ts = np.vstack([xs, ys]).T
    return ts

In [79]:
#Print simulation 1
example1= get_exemplar_1(100)
example1

array([[1, 1],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0,

In [80]:
#Compute mutual information and transfer entropy for case 1. The result is very similar
case1= get_timedelayed(example1,1)
case1

TimeDelayed(timedelayedMU=0.9833761901392236, transferE=0.983304093937157)

In [81]:
#Function for the second simulation. In this case the time series X and Y are always equal on time.
def get_exemplar_2(length, alphabet=2):

    xs = np.arange(length) % alphabet
    ts = np.vstack([xs, xs]).T
    return ts

In [82]:
#Print simulation 1
example2 = get_exemplar_2(100)
example2

array([[0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

In [83]:
#Compute mutual information and transfer entropy for case 1. We can see that conditioning on the past make transfer entropy equals to zero.
case2= get_timedelayed(example2,1)
case2

TimeDelayed(timedelayedMU=0.999926399368686, transferE=0.0)

In [84]:
#Function for the third simulation. In this case the time series X and Y use the exclusive OR operator in the present to produce Y in the future.
def get_exemplar_3(length):

    xs = np.random.randint(2, size=length)
    ys = [np.random.randint(2)]
    for x in xs[:-1]:
        ys.append(x ^ ys[-1])
    ts = np.vstack([xs, ys]).T
    return ts

In [85]:
#Print simulatioon 3
example3 = get_exemplar_3(100)
example3

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [1, 0],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 1],
       [1,

In [86]:
#Compute mutual information and transfer entropy for case 3. We can see that conditioning on the past make transfer entropy near to one while the time-delayed mutual information almost zero.
case3= get_timedelayed(syn,3)
case3

TimeDelayed(timedelayedMU=0.03979308630427081, transferE=0.9376985634739845)